### ISSUE TITLE
Theme Options Page - Error On Load

### ISSUE THREAD

**Issue by lucanos** [brianpurkiss/Whiteboard-Framework#1]
Running Whiteboard v3.1.4, Wordpress v3.2.1

After Activating the Whiteboard Theme, when attempting to access the Theme Options page, the following error message is shown (and no further page content).

Warning: call_user_func_array() [function.call-user-func-array]: First argument is expected to be a valid callback, 'theme_options_do_page' was given in C:\Program Files\XAMPP\htdocs\whiteboard\wp-includes\plugin.php on line 405

**Comment by brianpurkiss** [comment]
Have you made any modifications to functions.php?

**Comment by brianpurkiss** [comment]
I am not able to replicate that issue. 

Can you provide any additional information on the events leading up to that error?

**Comment by lucanos** [comment]
I just did a fresh pull of your GitHub Repo as at Commit b2fb6ed66f170c1feaca (v3.1.4) and the problem occurred again.

The events leading up to the error are quite straightforward:
1) Installed a fresh copy of Wordpress 3.2.1 within my XAMPP folder.
2) Setup Wordpress.
3) Added "whiteboard" folder from your Repo into the /wp-content/themes/ folder of the Wordpress install.
4) Logged into Wordpress Admin interface
5) Accessed the "Manage Themes" screen
6) Activated the Whiteboard Theme
7) Click on the "Theme Options" link now shown with the current Theme at the top of the "Manage Themes" screen.
8) Error seen as detailed above.

**Comment by brianpurkiss** [comment]
That's very strange that you would receive an error. Although, the Theme Options page actually has nothing currently in it. We should probably remove that from functions.php or at least comment it out if you want to add an options page.

This has been noted and will be addressed in in the next build.

In the mean time check out the Wordpress Codex. That should help you get going with creating a Theme Options page.
http://codex.wordpress.org/Creating_Options_Pages

**Comment by lucanos** [comment]
Thanks Brian. Both for your prompt response and for sharing this template with the community.
